ci:
  autofix_prs: true
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "chore: update pre-commit hooks"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-format
        types_or: [python, pyi]
