- start_pause_time: "22:30:00"
  stop_pause_time: "6:30:00"
  variance: "0:30:00"
- start_pause_time: "12:30:00"
  stop_pause_time: "16:30:00"
  variance: "0:30:00"
- start_pause_time: "2:30:00"
  stop_pause_time: "7:30:00"
  variance: "0:30:00"
- start_pause_time: "11:30:00"
  stop_pause_time: "13:30:00"
  variance: "0:30:00"
